source 'https://rubygems.org'

# Specify your gem's dependencies in rubyvernac-hindi.gemspec
gemspec

gem 'rake', '~> 13.0'

gem "yaml", "~> 0.2"

gem "dotenv", "~> 2.8"
gem "google-cloud-translate-v3", "~> 0.5"

gem 'rubyvernac-core', git: 'https://github.com/betacraft/rubyvernac-core', branch: "main"

group :development do
  gem "pry-nav", "~> 1.0"
end
