source 'https://rubygems.org'

# Specify your gem's dependencies in rubyvernac-__lang__.gemspec
gemspec

gem 'rake', '~> 10.3.2'

gem "pry", "~> 0.14.1"

gem "yaml", "~> 0.2.0"

gem "dotenv", "~> 2.8"
gem "google-cloud-translate-v3", "~> 0.5"

gem 'ruby-vernac-parser', git: 'https://github.com/betacraft/ruby-vernac-parser', branch: "main"
